export const siteConfig = {
    title: 'Tejaswi Anand — Cybersecurity Engineer & B.Tech Student at Delhi University',
    description: 'Portfolio of Tejaswi Anand, a B.Tech Computer Engineering student at Delhi University specializing in Cybersecurity, AI/ML, and Full-Stack Development. Built Eligify, Anomalyze (220 GB network threat detection), and Solar Swing.',
    url: 'https://thisistejaswi.in',
    ogImage: 'https://thisistejaswi.in/images/og-image.jpg',
    author: 'Tejaswi Anand',
    twitterHandle: '@tejasttam',
    keywords: [
        'Tejaswi Anand',
        'Tejaswi Anand portfolio',
        'Cybersecurity engineer Delhi',
        'B.Tech Computer Engineering Delhi University',
        'Faculty of Technology University of Delhi',
        'Eligify project',
        'Anomalyze project',
        'Solar Swing project',
        'cybersecurity student India',
        'AI ML developer',
        'Python developer portfolio',
        'network threat detection',
        'full stack developer India',
    ],
};
